require: 
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude: 
    - Guardfile
    - config/environments/*.rb

Style/Documentation:
  Exclude: [config/application.rb]

Layout/ArgumentAlignment: 
  Enabled: false

Lint/UselessAssignment:
  Enabled: false
